# Generated by Django 4.2 on 2023-04-29 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=11, region='EG'),
        ),
        migrations.CreateModel(
            name='Requester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('identification', models.PositiveIntegerField(max_length=14)),
                ('age', models.PositiveIntegerField(max_length=3)),
                ('working_status', models.CharField(max_length=20)),
                ('home_address', models.CharField(max_length=255)),
                ('work_address', models.CharField(max_length=255)),
                ('mob_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='EG')),
                ('home_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='EG')),
                ('marital_status', models.CharField(max_length=25)),
                ('family_count', models.PositiveIntegerField()),
                ('kids_count', models.PositiveIntegerField()),
                ('avg_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('gallery', models.ManyToManyField(blank=True, to='core.image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
