# Generated by Django 4.2 on 2023-05-03 01:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_region_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requester',
            name='home_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=8, null=True, region='EG'),
        ),
        migrations.AlterField(
            model_name='requester',
            name='mob_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=14, region='EG'),
        ),
    ]
