# Generated by Django 4.2 on 2023-05-03 01:20

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_requester_home_phone_alter_requester_mob_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requester',
            name='home_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=11, region='EG'),
        ),
    ]
