# Generated by Django 4.2 on 2023-05-03 01:37

import django.core.validators
from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_requester_home_phone_alter_requester_mob_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requester',
            name='home_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=11, region='EG', unique=True, validators=[django.core.validators.RegexValidator(message='Home phone number must be 8 digits', regex='^[0-9]{8}$')]),
        ),
    ]
