# Generated by Django 4.2 on 2023-05-03 01:40

import django.core.validators
from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_requester_home_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requester',
            name='home_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=11, region='EG', unique=True, validators=[django.core.validators.RegexValidator(regex='^[0-9]{10}$')]),
        ),
    ]
