# Generated by Django 4.2 on 2023-05-03 01:54

import django.core.validators
from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_requester_home_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requester',
            name='home_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='EG', validators=[django.core.validators.RegexValidator(message='Home phone number must be in the format +20xxxxxxxx', regex='^\\+20[0-9]{8}$')]),
        ),
    ]
